 {
  "listmanga":[
{
"view_manga_a4":"หน้าที่1",
"view_manga":"https://ilovedoujin.com/i/1493/001.jpg"
    },
{
"view_manga_a4":"หน้าที่2",
"view_manga":"https://ilovedoujin.com/i/1493/002.jpg"
    },
{
"view_manga_a4":"หน้าที่3",
"view_manga":"https://ilovedoujin.com/i/1493/003.jpg"
    },
{
"view_manga_a4":"หน้าที่4",
"view_manga":"https://ilovedoujin.com/i/1493/004.jpg"
    },
{
"view_manga_a4":"หน้าที่5",
"view_manga":"https://ilovedoujin.com/i/1493/005.jpg"
    },
{
"view_manga_a4":"หน้าที่6",
"view_manga":"https://ilovedoujin.com/i/1493/006.jpg"
    },
{
"view_manga_a4":"หน้าที่7",
"view_manga":"https://ilovedoujin.com/i/1493/007.jpg"
    }
  ]
}