 {
  "listmanga":[
{
"view_manga_a4":"หน้าที่1",
"view_manga":"https://ilovedoujin.com/i/1497/001.jpg"
    },
{
"view_manga_a4":"หน้าที่2",
"view_manga":"https://ilovedoujin.com/i/1497/002.jpg"
    },
{
"view_manga_a4":"หน้าที่3",
"view_manga":"https://ilovedoujin.com/i/1497/003.jpg"
    },
{
"view_manga_a4":"หน้าที่4",
"view_manga":"https://ilovedoujin.com/i/1497/004.jpg"
    },
{
"view_manga_a4":"หน้าที่5",
"view_manga":"https://ilovedoujin.com/i/1497/005.jpg"
    },
{
"view_manga_a4":"หน้าที่6",
"view_manga":"https://ilovedoujin.com/i/1497/006.jpg"
    },
{
"view_manga_a4":"หน้าที่7",
"view_manga":"https://ilovedoujin.com/i/1497/007.jpg"
    }
  ]
}