 {
  "listmanga":[
{
"view_manga_a4":"หน้าที่1",
"view_manga":"https://ilovedoujin.com/i/1074/001.jpg"
    },
{
"view_manga_a4":"หน้าที่2",
"view_manga":"https://ilovedoujin.com/i/1074/002.jpg"
    },
{
"view_manga_a4":"หน้าที่3",
"view_manga":"https://ilovedoujin.com/i/1074/003.jpg"
    },
{
"view_manga_a4":"หน้าที่4",
"view_manga":"https://ilovedoujin.com/i/1074/004.jpg"
    },
{
"view_manga_a4":"หน้าที่5",
"view_manga":"https://ilovedoujin.com/i/1074/005.jpg"
    },
{
"view_manga_a4":"หน้าที่6",
"view_manga":"https://ilovedoujin.com/i/1074/006.jpg"
    },
{
"view_manga_a4":"หน้าที่7",
"view_manga":"https://ilovedoujin.com/i/1074/007.jpg"
    },
{
"view_manga_a4":"หน้าที่8",
"view_manga":"https://ilovedoujin.com/i/1074/008.jpg"
    },
{
"view_manga_a4":"หน้าที่9",
"view_manga":"https://ilovedoujin.com/i/1074/009.jpg"
    },
{
"view_manga_a4":"หน้าที่10",
"view_manga":"https://ilovedoujin.com/i/1074/010.jpg"
    },
{
"view_manga_a4":"หน้าที่11",
"view_manga":"https://ilovedoujin.com/i/1074/011.jpg"
    },
{
"view_manga_a4":"หน้าที่12",
"view_manga":"https://ilovedoujin.com/i/1074/012.jpg"
    }
  ]
}